/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per.wlj.database.ui;

import java.util.HashMap;
import java.util.Map;

import per.wlj.database.datasource.impl.DataSourceFactory;
import per.wlj.database.util.BuilderContext;

/**
 *
 * @author WILLJOE
 */
public class DatabaseUI extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form DatabaseUI
     */
    public DatabaseUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceCombo = new javax.swing.JComboBox();
        sourceLabel = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();
        targetCombo = new javax.swing.JComboBox();
        sourceDriverLabel = new javax.swing.JLabel();
        sourceURLLabel = new javax.swing.JLabel();
        sourceUsernameLabel = new javax.swing.JLabel();
        sourcePasswordLabel = new javax.swing.JLabel();
        sourceDatabaseNameLabel = new javax.swing.JLabel();
        sourceDriver = new javax.swing.JTextField();
        sourceURL = new javax.swing.JTextField();
        sourceUsername = new javax.swing.JTextField();
        sourcePassword = new javax.swing.JTextField();
        sourceDatabaseName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        sourceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oracle", "mysql" }));
        sourceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceComboActionPerformed(evt);
            }
        });

        sourceLabel.setText("源数据库");

        targetLabel.setText("目标数据库");

        targetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "oracle", "mysql" }));

        sourceDriverLabel.setText("源数据库驱动");

        sourceURLLabel.setText("源数据库URL");

        sourceUsernameLabel.setText("源数据库用户名");

        sourcePasswordLabel.setText("源数据库密码");

        sourceDatabaseNameLabel.setText("源数据库名称");

        sourceURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceURLActionPerformed(evt);
            }
        });

        jButton1.setText("生效");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sourceLabel)
                        .addGap(16, 16, 16)
                        .addComponent(sourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(targetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(targetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sourceDriverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sourceURLLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sourceUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sourcePasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sourceDatabaseNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceDriver)
                            .addComponent(sourceURL)
                            .addComponent(sourceUsername)
                            .addComponent(sourcePassword)
                            .addComponent(sourceDatabaseName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceLabel)
                    .addComponent(targetLabel)
                    .addComponent(targetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceDriverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceURLLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourcePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourcePasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceDatabaseNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sourceComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceComboActionPerformed

    private void sourceURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceURLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	Map<String ,String> dbs = getDBInformations();
        BuilderContext.getInstance().putParams("DB_INFORMATIONS", dbs);
        if(null ==  dbs.get("SOURCE_URL") || "".equals(dbs.get("SOURCE_URL"))){
        	 DataSourceFactory.getInstance().createDataSource(dbs.get("SOURCE_TYPE"));
        }else{
        	DataSourceFactory.getInstance().buildDataSource(dbs.get("SOURCE_TYPE"), dbs.get("SOURCE_DRIVER"), dbs.get("SOURCE_URL"), dbs.get("SOURCE_USERNAME"), dbs.get("PASSWORD"));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Map<String, String> getDBInformations(){
        Map<String ,String> dbInformations = new HashMap<String, String>();
        String sourceDbType = (String)this.sourceCombo.getSelectedItem();
        String targetDbType = (String)this.targetCombo.getSelectedItem();
        String sourceDriver = this.sourceDriver.getText();
        String sourceUrl = this.sourceURL.getText();
        String sourceUsername = this.sourceUsername.getText();
        String sourcePassword = this.sourcePassword.getText();
        String sourceDbName = this.sourceDatabaseName.getText();
        
        dbInformations.put("SOURCE_TYPE", sourceDbType);
        dbInformations.put("TARGET_TYPE", targetDbType);
        dbInformations.put("SOURCE_DRIVER", sourceDriver);
        dbInformations.put("SOURCE_URL", sourceUrl);
        dbInformations.put("SOURCE_USERNAME", sourceUsername);
        dbInformations.put("SOURCE_PASSWORD", sourcePassword);
        dbInformations.put("SOURCE_DB_NAME", sourceDbName);
        
        return dbInformations;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox sourceCombo;
    private javax.swing.JTextField sourceDatabaseName;
    private javax.swing.JLabel sourceDatabaseNameLabel;
    private javax.swing.JTextField sourceDriver;
    private javax.swing.JLabel sourceDriverLabel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JTextField sourcePassword;
    private javax.swing.JLabel sourcePasswordLabel;
    private javax.swing.JTextField sourceURL;
    private javax.swing.JLabel sourceURLLabel;
    private javax.swing.JTextField sourceUsername;
    private javax.swing.JLabel sourceUsernameLabel;
    private javax.swing.JComboBox targetCombo;
    private javax.swing.JLabel targetLabel;
    // End of variables declaration//GEN-END:variables
}
