/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per.wlj.database.ui;

import per.wlj.database.data.impl.DataExporter;
import per.wlj.database.util.BuilderContext;
import per.wlj.database.util.Constance;

/**
 *
 * @author WILLJOE
 */
public class DataExport extends javax.swing.JPanel {

	private static final long serialVersionUID = 298474415755998641L;
	/**
     * Creates new form DataExport
     */
    public DataExport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tableNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        startField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        limitField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lineLimitField = new javax.swing.JTextField();
        exportButton = new javax.swing.JButton();
        filePathField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("singtableName");

        tableNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("start");

        startField.setText("0");

        jLabel3.setText("limit");

        limitField.setText("-1");
        limitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("lineLimit");

        lineLimitField.setText("-1");

        exportButton.setText("EXPORT");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("filePath");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportButton)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tableNameField)
                        .addComponent(startField)
                        .addComponent(limitField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(lineLimitField))
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(startField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(limitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lineLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportButton)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNameFieldActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
            
    	if(null != this.threadHandler && this.threadHandler.isAlive()){
    		MainUI.log("running");
    		return;
    	}
    	
        
        Runnable export = new Runnable(){
            public void run(){
                Integer limit = -1;
                Integer start = 0;
                Integer lineLimit = -1;
                String singTableName = null;
                singTableName = tableNameField.getText();
                try{
                limit = Integer.valueOf(  limitField.getText());
                start = Integer.valueOf(  startField.getText());
                lineLimit = Integer.valueOf( lineLimitField.getText());
                }catch(Exception e){
                }finally{
                    long starttime = System.currentTimeMillis();
                    DataExporter de = new DataExporter();

                    String filePath = (String)BuilderContext.getInstance().getParams(Constance.KEY_DATA_PATH);
                    String fileName = (String)BuilderContext.getInstance().getParams(Constance.KEY_DATA_FILENAME);

                    if(null != filePath && !"".equals(filePath)){
                            de.setDataFilePath(filePath);
                    }
                    if(null != fileName && !"".equals(fileName)){
                            de.setDataFileName(fileName);
                    }
                    if(null != limit) de.setLimit(limit);
                    if(null != start) de.setStart(start);
                    if(null != lineLimit) de.setLineLimit(lineLimit);
                    if(null != singTableName && !"".equals(singTableName)) de.setSingleTableName(singTableName);
                    MainUI.log(singTableName);
                    de.buildData();
                    long end = System.currentTimeMillis();
                    System.out.println("Time used total: ["+((end - starttime)/1000.00)+"]");
                    MainUI.log("Time used total: ["+((end - starttime)/1000.00)+"]");
                }
            }
        };
        this.threadHandler =  new Thread(export);
        this.threadHandler.start();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void limitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportButton;
    private javax.swing.JTextField filePathField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField limitField;
    private javax.swing.JTextField lineLimitField;
    private javax.swing.JTextField startField;
    private javax.swing.JTextField tableNameField;
    private Thread threadHandler ;
    // End of variables declaration//GEN-END:variables
}
